Description: Prereqs for Web

Parameters:
  ZoneDomainName:
    Type: String
    Default: 'cloudcoffeebreak.com'

Outputs:
  CertificateArn:
    Value: !Ref Certificate
    Export:
      Name: CloudCoffeeBreakCertificate

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref ZoneDomainName

  Certificate:
    Type: AWS::CertificateManager::Certificate
    DependsOn: HostedZone
    Properties:
      DomainName: !Sub '*.${ZoneDomainName}'
      SubjectAlternativeNames:
        - !Ref ZoneDomainName
      ValidationMethod: DNS

